spring.application.name=memgraph-api

# Use environment variable instead of hardcoding
spring.ai.openai.api-key=${GROQ_API_KEY}

# Groq endpoint
spring.ai.openai.base-url=https://api.groq.com/openai

# Model
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile